### PR TITLE
Add Readme and License

### PR DESCRIPTION
**Pull request by josephfung**
Added a draft readme file and license - completely open to discussion on a) anything that should be added to the readme, and b) if the MIT license is the best license to make this available under.

### CODE REVIEW

**Comment by iniq** [comment]
Should that discussion happen before or after merging?

**Comment by josephfung** [comment]
Before is better.

**Comment by iniq** [comment]
The readme seems fine for now, might have more thoughts if we get farther into it.
No idea on the license

**Comment by egerlach** [comment]
Given that CakePHP is released under the MIT license, I give the license a +1. My only other suggestion would be the LGPL, but I'm partial to that one.

**Comment by egerlach** [comment]
@josephfung Given that @iniq and I have approved this, you can merge at your leisure. The reason I'm leaving it to you is so you can finalize anything with the license.

**Pull request merged**
